name: Run Gradle Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
      java-version: '21'
      distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        develocity-access-key: ${{ secrets.DV_ACCESS_TOKEN }}
    - name: Build with Gradle
      run: ./gradlew clean build
