name: Run Gradle Build

on:
  schedule:
  - cron: "0 1 * * *"
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 7edddb6842c8f2356fda013b352525a78f9f8f04
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        develocity-url: 'https://develocity-field.gradle.com'
        develocity-access-key: ${{ secrets.DV_ACCESS_TOKEN }}
    - name: Build with Gradle
      run: ./gradlew clean build
